apiVersion: v1
kind: ConfigMap
metadata:
  namespace: production
  name: envs-production-postgres-new
data:
  DATABASE_TYPE: PostgreSQL
  POSTGRES_DB: Platform_DB
  POSTGRES_HOST: pgbouncer-service
  POSTGRES_HOST_INNER: postgres15-new
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres_user