apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: uat
  name: computation-storage-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: pv-secrets
    shareName: computationshare-uat
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=70070  # as in compose/production/django/Dockerfile
  - gid=70070
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uat
  name: computation-storage-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: computation-storage-azurefile
  resources:
    requests:
      storage: 10Gi
