apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: uat
  name: media-azurefile1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: pv-secrets
    shareName: mediashare-uat
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=70070  # as in compose/production/django/Dockerfile
  - gid=70070
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uat
  name: media-azurefile1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: media-azurefile1
  resources:
    requests:
      storage: 100Gi
