apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uat
  name: postgresql-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: retain-azure-disk
  resources:
    requests:
      storage: 1Gi
status: {}
