apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: uat
  name: postgres-backups
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default  # managed-premium is preferred however expensive.
  resources:
    requests:
      storage: 5Gi
status: {}
