#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#systemctl enable rqscheduler.service
#systemctl start rqscheduler.service
rq worker system_scheduled_job_queue -u ${REDIS_URL_SCHEDULER} --with-scheduler