apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt2
spec:
  acme:
    email: srijanraychaudhuri@acies.consulting
    privateKeySecretRef:
      name: letsencrypt2
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx