trigger:
- development
resources:
- repo: self
variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: trivy-scan-conn
  imageRepository: 'revolutio_kubernetes/revolutio'
  workerimageRepository: 'revolutio_kubernetes/worker'
  containerRegistry: 'revolutiodev.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  imagePullSecret: 'revolutio9647b8fc-auth'
  tag: $(Build.BuildNumber)
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  azureSubscriptionEndpoint: revolutio-acr-connection

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/revolutio:latest
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio/arrowflight:latest
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/nginx:latest
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/rqscheduler:latest
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/postgres:15-bullseye
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/keydb:latest
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true
- task: trivy@1
  inputs:
    image: revolutiodev.azurecr.io/revolutio_kubernetes/redis:5.0.4-stretch
    exitcode: 0
    loginDockerConfig: true
    options: --timeout 50m0s
    ignoreUnfixed: true