version: "3.8"

services:
  redis:
    env_file:
      - ".env"
    image: "redis:5.0.4-stretch"
    restart: always
    stop_grace_period: 3s
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=Platform_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: "."
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python3 manage.py collectstatic --no-input; python3 manage.py makemigrations; python3 manage.py migrate; uvicorn config.asgi:application --port 5000 --host 0.0.0.0 '
    depends_on:
      - "redis"
      - "postgres"
    env_file:
      - ".env"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8000/login}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:5000}:5000"
    restart: always
    stop_grace_period: 3s
    volumes:
      - "${DOCKER_WEB_VOLUME:-./revolutio.conf:/opt/revolutio/revolutio.conf}"
      - static:/opt/revolutio/kore_investment/static
      - user_defined_template:/revolutio/kore_investment/templates/user_defined_template
      - user_migration:/revolutio/kore_investment/users/migrations

  monitor:
    build: .
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        rqmonitor -b monitor -p 8899 -u ${REDIS_URL}
    restart: always
    volumes:
      - "${DOCKER_WEB_VOLUME:-./revolutio.conf:/opt/revolutio/revolutio.conf}"
    ports:
      - "8899:8899"
    env_file:
        - ".env"
    depends_on:
      - redis
      - web
    init: true

  worker:
    build:
      context: "."
    command: celery -A config worker --pool=gevent --concurrency=500
    depends_on:
      - "redis"
      - "web"
      - "postgres"
    env_file:
      - ".env"
    restart: always
    stop_grace_period: 3s
    volumes:
      - "${DOCKER_WEB_VOLUME:-./revolutio.conf:/opt/revolutio/revolutio.conf}"
  nginx:
    build: ./nginx
    command: nginx -g "daemon off;"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - web
    volumes:
      - "${DOCKER_NGINX_VOLUME:-./nginx/nginx.conf:/etc/nginx/nginx.conf}"
      - static:/var/www/revolutio/static
      #- "${DOCKER_SSL_CERT:-./Kepler/cert.pem:/etc/ssl/cert.pem}"
      #- "${DOCKER_SSL_KEY:-./Kepler/ssl.key:/etc/ssl/ssl.key}"

volumes:
  redis:
  postgresql-data:
  static:
  user_defined_template:
  user_migration:
