trigger:
- development
resources:
- repo: self
variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b90f91b1-9756-42a5-a0bb-e34d1f1f8b48'
  imageRepository: 'revolutio_kubernetes/revolutio'
  workerimageRepository: 'revolutio_kubernetes/worker'
  containerRegistry: 'revolutio.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  imagePullSecret: 'revolutio9647b8fc-auth'
  tag: $(Build.BuildNumber)
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  azureSubscriptionEndpoint: revolutio-acr-connection

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and update CDN
  jobs:
  - job: Build
    displayName: Build and update CDN
    timeoutInMinutes: 120
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build and update CDN
      inputs:
        action: Build services
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: docker-compose-collectstatic.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(tag)