# Generated by Django 4.0.10 on 2023-07-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="system_application_master",
            name="users_syste_instanc_0fa6c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="system_application_master",
            name="users_syste_app_nam_dc64bf_idx",
        ),
        migrations.RemoveField(
            model_name="system_application_master",
            name="instance",
        ),
    ]
