# Generated by Django 4.0.10 on 2023-07-20 04:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_system_application_master_users_syste_instanc_0fa6c9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="applicationAccess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=256, null=False)),
                ("app_code", models.CharField(max_length=256, null=False)),
                (
                    "instance",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.instance"),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
