apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: worker
  namespace: production
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        service: worker
    spec:
      containers:
      - args:
        - /rqworker/start
        image: revolutio.azurecr.io/revolutio_kubernetes/revolutio:20231101.4
        name: rqworker
        envFrom:
          - configMapRef:
              name: envs-production-django
          - configMapRef:
              name: envs-production-postgres-new
          - secretRef:
              name: secrets-production-django
          - secretRef:
              name: secrets-production-postgres-new
        env:
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
          - name: REDIS_URL
            value: $(REDIS_URL)
          - name: TZ
            value: UTC
        resources:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 1.0
            memory: 2Gi
        volumeMounts:
          - mountPath: /opt/revolutio/static
            name: static-azurefile
          - mountPath: /opt/revolutio/kore_investment/templates/user_defined_template
            name: templates-azurefile
          - mountPath: /opt/revolutio/Platform_Configs
            name: platformconfig-azurefile
          - mountPath: /opt/revolutio/Computation_Temp_Storage
            name: computation-storage-azurefile
      nodeSelector:
          poolclass: workerpool
      restartPolicy: Always
      volumes:
        - name: static-azurefile
          persistentVolumeClaim:
            claimName: static-azurefile
        - name: templates-azurefile
          persistentVolumeClaim:
            claimName: templates-azurefile
        - name: platformconfig-azurefile
          persistentVolumeClaim:
            claimName: platformconfig-azurefile
        - name: computation-storage-azurefile
          persistentVolumeClaim:
            claimName: computation-storage-azurefile

