from django.urls import path, re_path

from kore_investment.users.Email import o365
from kore_investment.users.views import error_404_view, user_detail_view, user_redirect_view, user_update_view
from kore_investment.utils.decorators import login_required

from . import views
from .plotly import plotly_backend

app_name = "users"
urlpatterns = [
    path("termsofuse/", login_required(views.termsOfUse), name="termsofuse"),
    re_path(r"^selectApplication/$", login_required(views.select_application), name="select_application"),
    re_path(r"^adminPanel/$", login_required(views.admin_panel), name="admin_panel"),
    re_path(r"^alertsSetup/$", login_required(views.alerts_setup), name="alerts_setup"),
    re_path(r"^customizeTheme/$", login_required(views.customize_theme), name="customize_theme"),
    re_path(r"^dashboard/$", login_required(views.dashboard), name="dashboard"),
    re_path(r"^selectDashboard/$", login_required(views.selectDashboard), name="selectDashboard"),
    re_path(
        r"^(?P<app_code>[\w-]+)/previewTheme/(?P<theme_type>[\w-]+)/$",
        login_required(views.preview_theme),
        name="preview_theme",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/homePage/$",
        login_required(views.displayHomePage),
        name="homePage",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/developer_tools/$",
        login_required(views.developer_tools),
        name="developer_tools",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/homePage/Grapejs$",
        login_required(views.GrapesJsView),
        name="GrapesJsView",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/homePage/Grapejs/asset-upload/$",
        login_required(views.grapes_js_asset_manager),
        name="grapes_js_asset_manager",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/homePage/Grapejs/preview/$",
        login_required(views.HomePage_preview),
        name="HomePage_preview",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/staticPage/asset-upload/$",
        login_required(views.grapes_js_asset_manager_static),
        name="grapes_js_asset_manager_static",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/customView/$",
        login_required(views.customView),
        name="customView",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/dynamicVal/",
        login_required(views.dynamicVal),
        name="dynamicVal",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/asyncFunction/",
        login_required(views.asyncFunction),
        name="asyncFunction",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api_integration/$",
        login_required(views.api_integration),
        name="api_integration",
    ),
    re_path(r"^o365login/$", login_required(o365.auth_step_one), name="auth_step_one"),
    re_path(
        r"^o365login_step2/$", login_required(o365.auth_step_two_callback), name="auth_step_two_callback"
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/permission_access/$",
        login_required(views.permission_access),
        name="permission_access",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/$",
        login_required(views.user_management),
        name="user_management",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/fetch_user_server_side/$",
        login_required(views.fetch_user_server_side),
        name="fetch_user_server_side",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/approval_table/$",
        login_required(views.approval_table),
        name="approval_table",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/approval_table-ima/$",
        views.approval_table_inmail,
        name="approval_table_inmail",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/alert_management/$",
        login_required(views.alert_management),
        name="alert_management",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/userpermissionapproval/$",
        login_required(views.userpermissionapproval),
        name="userpermissionapproval",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/userpermissionrejection/$",
        login_required(views.userpermissionrejection),
        name="userpermissionrejection",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/business_model/$",
        login_required(views.business_model),
        name="business_model",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/pivot_report_data/$",
        login_required(views.pivot_report_data),
        name="pivot_report_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/create_new_pivot_report/$",
        login_required(views.create_new_pivot_report),
        name="create_new_pivot_report",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/current_pivot_report/(?P<pk>\d+)/$",
        login_required(views.current_pivot_report),
        name="current_pivot_report",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/subprocess_not_found/$",
        login_required(views.subprocess_not_found),
        name="subprocess_not_found",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/permission_denied/$",
        login_required(views.permission_denied),
        name="permission_denied",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/application/$",
        login_required(views.application),
        name="application",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/application_order/$",
        login_required(views.application_order),
        name="application_order",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/comparable_get_data/$",
        login_required(views.comparable_get_data),
        name="comparable_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/model_def_get_data/$",
        login_required(views.model_def_get_data),
        name="model_def_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/standard_update_save_master_form_modeldef/$",
        login_required(views.standard_update_save_master_form_modeldef),
        name="standard_update_save_master_form_modeldef",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/constriant_get_data/$",
        login_required(views.constriant_get_data),
        name="constriant_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/asset_grouping_get_data/$",
        login_required(views.asset_grouping_get_data),
        name="asset_grouping_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/filteredtables/$",
        login_required(views.assetgroupingfiltereddata),
        name="assetgroupingfiltereddata",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/audit_trail/$",
        login_required(views.audit_trail),
        name="audit_trail",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/create/$",
        login_required(views.groupcreate),
        name="groupcreate",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/assign/$",
        login_required(views.usergrouptag),
        name="grouptag",
    ),
    re_path(r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/ocr/$", login_required(views.ocr), name="ocr"),
    re_path(r"^planner/$", login_required(views.planner_kanban), name="planner"),
    re_path(r"^plannerAPI/$", views.PlannerAPI.as_view(), name="plannerAPI"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/planner/$",
        login_required(views.planner_kanban),
        name="plannerApp",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/plannerAPI/$",
        views.PlannerAPI.as_view(),
        name="plannerAppAPI",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/(?P<pk>\d+)/$",
        login_required(views.access_setupdetailview),
        name="access_setupdetail",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_management/user_logout/(?P<id>\d+)/$",
        login_required(views.user_logout),
        name="user_logout",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/update_user_password/$",
        login_required(views.update_user_password_method),
        name="change_user-password",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/DataManagement/$",
        login_required(views.DataManagement),
        name="datamanagement",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/ReportCreation/$",
        login_required(views.ReportCreation),
        name="reportcreation",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/import_tables/$",
        login_required(views.import_tables),
        name="import_tables",
    ),
    re_path(r"^data_api/(?P<tablename>[\w-]+)/$", views.data_API.as_view(), name="data_api"),
    re_path(r"^data_push_api/$", views.data_push_API.as_view(), name="data_push_api"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/export_tables/$",
        login_required(views.export_tables),
        name="export_tables",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/tables/",
        login_required(views.TablesListCreate.as_view()),
        name="rest_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/relationship/",
        login_required(views.RelationshipListCreate.as_view()),
        name="relationship_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/hierarchy/",
        login_required(views.HierarchyListCreate),
        name="hierarchy_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/hierarchy_group/",
        login_required(views.HierarchyGroupListCreate.as_view()),
        name="hierarchy_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/hierarchy_data/",
        login_required(views.hierarchy_data),
        name="hierarchy_data_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/hierarchy_level_info/",
        login_required(views.hierarchy_level_info),
        name="hierarchy_level_info",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/relationship_level_info/",
        login_required(views.relationship_level_info),
        name="relationship_level_info",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/hierarchy_uploads/",
        login_required(views.hierarchy_uploads),
        name="hierarchy_uploads",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/api/add_hierarchy/",
        login_required(views.AddHierarchyListCreate.as_view()),
        name="add_hierarchy_api",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/plotly/$",
        login_required(plotly_backend.plotlyTrials),
        name="plotly",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/plotlyPlots/$",
        login_required(views.render_plot),
        name="plotlyPlots",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/create_filter_inputs/$",
        login_required(plotly_backend.create_filter_inputs),
        name="create_filter_inputs",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/plotly_interaction/$",
        login_required(plotly_backend.plotly_interaction),
        name="plotly_interaction",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/filter_plot/$",
        login_required(plotly_backend.filter_plot),
        name="filterPlots",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/export_data/$",
        login_required(plotly_backend.export_data),
        name="export_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/upload_image/$",
        login_required(plotly_backend.upload_image),
        name="upload_image",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/upload_bg_image/$",
        login_required(plotly_backend.upload_bg_image),
        name="upload_bg_image",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/reload_bg_image/$",
        login_required(plotly_backend.reload_bg_image),
        name="reload_bg_image",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/delete_image/$",
        login_required(plotly_backend.delete_image),
        name="delete_image",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/drilldown_plot/$",
        login_required(plotly_backend.drilldown_plot),
        name="drilldownPlots",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/viewfilter/$",
        login_required(views.viewfilter),
        name="viewfilter",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_login_insights/$",
        login_required(views.user_login_insights),
        name="user_login_insights",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/data_operation_insights/$",
        login_required(views.data_operation_insights),
        name="data_operation_insights",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/rollup_view_get_data/$",
        login_required(views.rollup_view_get_data),
        name="rollup_view_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_activity_insights/default/$",
        login_required(views.user_activity_insights),
        name="user_activity_insights",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_activity_insights/urlView/$",
        login_required(views.url_view_get_data),
        name="url_view_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_activity_insights/userView/$",
        login_required(views.username_view_get_data),
        name="username_view_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_activity_insights/sessionView/$",
        login_required(views.sessionID_view_get_data),
        name="sessionID_view_get_data",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/search_create_view/$",
        login_required(views.search_create_view),
        name="search_create_view",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/audit/$",
        login_required(views.Audit_tracking_refresh),
        name="audit",
    ),
    path("auditview/", views.ViewAuditTracking.as_view(), name="ViewAuditTracking"),
    path("profile/", login_required(views.user_profile), name="userprofile"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/profile/",
        login_required(views.user_profile),
        name="userprofileApp",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/smtp_management/$",
        login_required(views.smtp_management),
        name="smtp_management",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/userConfigSave/$",
        login_required(views.userConfigSave),
        name="userConfigSave",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/userConfigLoad/$",
        login_required(views.userConfigLoad),
        name="userConfigLoad",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/alertModel/$",
        login_required(views.alert_entity),
        name="alert_model",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/systemvalues/$",
        login_required(views.SystemValues),
        name="values",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/scheduler_post/$",
        login_required(views.scheduler_post),
        name="scheduler_post",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/lvlcreation/$",
        login_required(views.lvlcreation),
        name="lvlcreation",
    ),
    path("changeprofilename/", login_required(views.changeprofilename), name="changeprofilename"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/permissionapproval/$",
        login_required(views.permissionapproval),
        name="permissionapproval",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/requestlevel4access/$",
        login_required(views.requestlevel4access),
        name="requestlevel4access",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/usercreate/$",
        login_required(views.usercreate),
        name="usercreate",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/user_update/$",
        login_required(views.user_update),
        name="user_update",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/values/$", login_required(views.values), name="systemvalues"
    ),
    re_path(r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/access1/$", login_required(views.access1), name="access1"),
    re_path(r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/config2/$", login_required(views.config2), name="config2"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/ajax/tabConfig/",
        login_required(views.tab_config),
        name="tab_config",
    ),
    re_path(
        r"^ajax/profilephoto_upload/$", login_required(views.upload_user_photo), name="upload_user_photo"
    ),
    re_path(
        r"^ajax/coverphoto_upload/$", login_required(views.upload_cover_photo), name="upload_cover_photo"
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/processCreation/$",
        login_required(views.processCreation),
        name="processCreation",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/reset_navigation_waypoints/$",
        login_required(views.reset_waypoint_config),
        name="reset_navigation_waypoints",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/Levelcreation/$",
        login_required(views.LevelCreation),
        name="LevelCreation",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/FlowMonitor/$",
        login_required(views.FlowMonitor),
        name="FlowMonitor",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/staticPage/$",
        login_required(views.staticPage),
        name="staticPage",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/preview/$",
        login_required(views.staticPage_preview),
        name="staticPage_preview",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/htmlgeneratorall/$",
        login_required(views.htmlgeneratorall),
        name="htmlgeneratorall",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/web_socket/$",
        login_required(views.index_web_socket),
        name="index",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/web_socket/(?P<room_name>\w+)/$",
        login_required(views.room_web_socket),
        name="room",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/processGraphModule/$",
        login_required(views.processGraphModule),
        name="processGraphModule",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/processGraphModule/preview/$",
        login_required(views.DesignPage_preview),
        name="DesignPage_preview",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/processCreationsave/$",
        login_required(views.XmlFlowchart),
        name="saveprocess",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/processGraphModuleOpen/$",
        login_required(views.OpenFlowchart),
        name="openflowchart",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/computationModule/$",
        login_required(views.computation_module),
        name="computation_module",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/computationModule/upload-handler/$",
        login_required(views.computation_module_upload_handler),
        name="computation_module_upload_handler",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/jobexecution/$",
        login_required(views.jobexecution),
        name="jobexecution",
    ),
    re_path(r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/job/$", login_required(views.job), name="job"),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/search_fields/$",
        login_required(views.search_fields),
        name="search_fields",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/in-app-approve/(?P<approval_code>[\w-]+)/(?P<action>[\w-]+)/(?P<redirect_code>[\w-]+)/$",
        login_required(views.in_app_approvals),
        name="in_app_approvals",
    ),
    # Currently Not using filedetails_uploadscreen function
    ##standardised urls
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/$",
        login_required(views.standardViewFunc),
        name="standard_model_view",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/create/$",
        login_required(views.standard_save_master_form),
        name="standard_save_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/createDraft/(?P<entry_type>[\w-]+)/(?P<row_id>[\w-]+)/$",
        login_required(views.standard_save_draft_master_form),
        name="standard_save_draft_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/create_file/$",
        login_required(views.standard_save_file_master_form),
        name="standard_save_file_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/multiupload/$",
        login_required(views.standardViewFunc),
        name="standard_upload_view",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/serverside_search/$",
        login_required(views.serverside_search),
        name="serverside_search",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/computation-server-side/(?P<computation_id>[\w-]+)$",
        login_required(views.computation_server_side),
        name="computation_server_side",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/delete/(?P<pk>\d+)/$",
        login_required(views.standard_delete_master_form),
        name="standard_delete_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/update/(?P<pk>\d+)/$",
        login_required(views.standard_update_master_form),
        name="standard_update_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/update_save/(?P<pk>\d+)/$",
        login_required(views.standard_update_save_master_form),
        name="standard_update_save_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/update_save_history/(?P<pk>\d+)/$",
        login_required(views.standard_update_save_master_history_form),
        name="standard_update_save_master_history_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/update_save_constraint/(?P<pk>\d+)/$",
        login_required(views.standard_update_save_master_form_constraint),
        name="standard_update_save_master_form_constraint",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/update_save_flow_def/(?P<pk>\d+)/$",
        login_required(views.standard_update_save_master_form_flow),
        name="standard_update_save_master_form_flow",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/\w+/multi_update/$",
        login_required(views.standard_update_master_form),  # pure ajax method
        name="standard_update_save_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/\w+/multi_update_save/$",
        login_required(views.standard_multi_update_save_master_form),  # pure ajax method
        name="standard_multi_update_save_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/(?P<item_code>[\w-]+)/(?P<model_name>[\w-]+)/(?P<pk>\d+)/$",
        login_required(views.standard_detail_master_form),
        name="standard_detail_master_form",
    ),
    re_path(
        r"^(?P<app_code>[\w-]+)/(?P<mode>\w+)/get_datatable_data/(?P<elementTabID>[\w-]+)/(?P<model_name>[\w-]+)/(?P<view_name>([\w -]*))/$",
        login_required(views.server_side_content),
        name="server_side_content",
    ),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    re_path(r".*", view=error_404_view, name="404"),
]
