apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: postgres-data-new
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default  # managed-premium is preferred however expensive.
  resources:
    requests:
      storage: 50Gi
status: {}
