apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: postgresql-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: retain-azure-disk
  resources:
    requests:
      storage: 15Gi
status: {}
