# Generated by Django 3.2.11 on 2022-03-29 05:20

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220222_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="application_theme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("app_code", models.CharField(max_length=255, null=True)),
                ("theme_type", models.CharField(max_length=255, null=True)),
                ("theme_name", models.CharField(max_length=255, null=True)),
                ("theme_config", models.TextField(null=True)),
                ("created_by", models.CharField(max_length=100, null=True, verbose_name="Created by")),
                ("created_date", models.DateTimeField(auto_now=True, null=True, verbose_name="Created date")),
                ("modified_by", models.CharField(max_length=100, null=True, verbose_name="Modified by")),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Modified date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="audit_operation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=264, null=True)),
                ("operation", models.CharField(max_length=264, null=True)),
                ("message", models.CharField(max_length=264, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="template_theme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("template_name", models.CharField(max_length=255, null=True)),
                ("template_type", models.CharField(max_length=255, null=True)),
                ("template_config", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="theme_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="process_flow_model",
            name="redirect_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 3, 29, 5, 19, 37, 754302, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="tabscreens",
            name="fields",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="tabscreens",
            name="table_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 3, 29, 5, 19, 37, 784761, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
