# Generated by Django 3.2.11 on 2022-04-11 11:50

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220329_1050"),
    ]

    operations = [
        migrations.CreateModel(
            name="static_page_config",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("app_code", models.CharField(max_length=255, null=True)),
                ("tenant", models.CharField(max_length=255, null=True)),
                ("mode", models.CharField(max_length=255, null=True)),
                ("display_type", models.CharField(max_length=255, null=True)),
                ("config", models.TextField(null=True)),
                ("created_by", models.CharField(max_length=100, verbose_name="Created by")),
                ("created_date", models.DateTimeField(auto_now=True, verbose_name="Created date")),
                ("modified_by", models.CharField(max_length=100, null=True, verbose_name="Modified by")),
                (
                    "modified_date",
                    models.DateTimeField(max_length=100, null=True, verbose_name="Modified date"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="breadcrumbs",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userpermission_interim",
            name="level_button_access",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userpermission_master",
            name="level_button_access",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="audit_operation",
            name="message",
            field=models.CharField(max_length=2640, null=True),
        ),
        migrations.AlterField(
            model_name="audit_operation",
            name="url",
            field=models.CharField(max_length=526, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 4, 11, 11, 50, 5, 790950, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission_master",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("0", "Process"),
                    ("1", "Sub-process"),
                    ("2", "Category"),
                    ("3", "Category Button Access"),
                ],
                max_length=256,
                null=True,
                verbose_name="Permission level",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 4, 11, 11, 50, 5, 807501, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
