# Generated by Django 3.2.11 on 2022-04-25 11:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220411_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                upload_to="users/cover_photos",
                verbose_name="Cover photo (Note - Upload only jpg/png file)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
