# Generated by Django 3.2.11 on 2022-05-13 05:40

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220425_1721"),
    ]

    operations = [
        migrations.CreateModel(
            name="alerts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usergroup", models.CharField(max_length=256, null=True)),
                ("alert_owner", models.CharField(max_length=256, null=True)),
                ("approval_status", models.CharField(max_length=256, null=True)),
                ("approval_code", models.TextField(max_length=256, null=True)),
                ("alert_type", models.CharField(max_length=256, null=True)),
                ("alert_options", models.TextField(max_length=256, null=True)),
                ("events", models.TextField(max_length=256, null=True)),
                ("app_code", models.CharField(max_length=256, null=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("modified_by", models.CharField(max_length=100, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="failed_login_alerts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usergroup", models.CharField(max_length=256, null=True)),
                ("alert_owner", models.CharField(max_length=256, null=True)),
                ("alert_options", models.TextField(max_length=256, null=True)),
                ("app_code", models.CharField(max_length=256, null=True)),
                ("events", models.TextField(max_length=256, null=True)),
                ("approval_status", models.CharField(max_length=256, null=True)),
                ("approval_code", models.TextField(max_length=256, null=True)),
                ("created_by", models.CharField(max_length=100, null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("modified_by", models.CharField(max_length=100, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="approval_email",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="no_of_alert",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approval_code",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="static_page_config",
            name="code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="no_of_alert",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 5, 13, 5, 40, 9, 560622, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 5, 13, 5, 40, 9, 580638, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
