# Generated by Django 3.2.11 on 2022-05-24 06:55

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20220513_1110"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="no_of_alert",
        ),
        migrations.AddField(
            model_name="profile",
            name="no_of_alert",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 5, 24, 6, 54, 29, 365641, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 5, 24, 6, 54, 29, 398772, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
