# Generated by Django 3.2.11 on 2022-07-11 11:15

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20220524_1225"),
    ]

    operations = [
        migrations.DeleteModel(
            name="alertbasetable",
        ),
        migrations.DeleteModel(
            name="CreditorOutstandingbalance",
        ),
        migrations.DeleteModel(
            name="list_of_scheduling_jobs",
        ),
        migrations.DeleteModel(
            name="Mobile",
        ),
        migrations.DeleteModel(
            name="Person_Web_Socket_Test",
        ),
        migrations.DeleteModel(
            name="Process_master",
        ),
        migrations.AddField(
            model_name="curve_data",
            name="transaction_id",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="curve_repository",
            name="transaction_id",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="holiday_calendar_repository",
            name="transaction_id",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="jobs_scheduled",
            name="schedule_type",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="schedule_process",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="scheduler_config",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="process_flow_model",
            name="run_left",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="process_flow_model",
            name="schedule_process",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tables",
            name="linked_table",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="facebook",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 7, 11, 11, 15, 18, 142349, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 7, 11, 11, 15, 18, 156428, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
