# Generated by Django 3.2.11 on 2022-07-12 05:48

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20220711_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="dashboard_config",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("app_code", models.CharField(max_length=255, null=True)),
                ("application_name", models.CharField(max_length=255, null=True)),
                ("subprocess_code", models.CharField(max_length=255, null=True)),
                ("subprocess_name", models.CharField(max_length=255, null=True)),
                ("element_id", models.CharField(max_length=255, null=True)),
                ("config_id", models.CharField(max_length=255, null=True)),
                ("dashboard_type", models.CharField(max_length=255, null=True)),
                ("dashboard_id", models.CharField(max_length=255, null=True)),
                ("dashboard_config_id", models.CharField(max_length=255, null=True)),
                ("edit_type", models.CharField(max_length=255, null=True)),
                ("tab_id", models.CharField(max_length=255, null=True)),
                ("tab_name", models.CharField(max_length=255, null=True)),
                ("plots_id", models.CharField(max_length=255, null=True)),
                ("plots_name", models.CharField(max_length=255, null=True)),
                ("shared_username", models.CharField(max_length=255, null=True)),
                ("shared_type", models.CharField(max_length=255, null=True)),
                ("subprocess_group", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 7, 12, 5, 47, 27, 719787, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 7, 12, 5, 47, 27, 748919, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
