# Generated by Django 3.2.11 on 2022-08-06 06:28

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20220712_1118"),
    ]

    operations = [
        migrations.CreateModel(
            name="alertslog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usergroup", models.CharField(max_length=256, null=True)),
                ("alert_owner", models.CharField(max_length=256, null=True)),
                ("alert_type", models.CharField(max_length=256, null=True)),
                ("alert_options", models.TextField(max_length=256, null=True)),
                ("events", models.TextField(max_length=256, null=True)),
                ("alert_message", models.TextField(max_length=256, null=True)),
                ("app_code", models.CharField(max_length=256, null=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="hierarchy_group",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="type_of_approval",
            field=models.CharField(default="static", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="tabscreens",
            name="user_configuration",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userconfig",
            name="shared_config",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 8, 6, 6, 27, 27, 330326, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 8, 6, 6, 27, 27, 360732, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
