# Generated by Django 4.0.7 on 2022-08-23 10:18

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20220806_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard_config",
            name="dashboard_index",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 8, 23, 10, 17, 27, 145152, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 8, 23, 10, 17, 27, 170820, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
