# Generated by Django 4.0.7 on 2022-09-02 07:20

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_dashboard_config_dashboard_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_hash",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 9, 2, 7, 19, 59, 131457, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 9, 2, 7, 19, 59, 144266, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
