# Generated by Django 4.0.7 on 2022-11-12 07:06

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_dashboard_config_tenant_user_mfa_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessScheduler",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("app_code", models.CharField(max_length=50)),
                ("item_code", models.CharField(max_length=50)),
                ("item_group_code", models.CharField(max_length=50)),
                ("element_id", models.CharField(max_length=50, null=True, unique=True)),
                ("scheduler_type", models.CharField(max_length=20, null=True)),
                ("trigger_option", models.CharField(max_length=20, null=True)),
                ("dependent_block", models.CharField(max_length=50, null=True)),
                ("config", models.TextField(null=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="navigationsidebar",
            name="schedule_process",
        ),
        migrations.RemoveField(
            model_name="navigationsidebar",
            name="scheduler_config",
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approval_decision_mailer_config",
            field=models.CharField(max_length=1026, null=True),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approver_user",
            field=models.CharField(max_length=1026, null=True),
        ),
        migrations.AddField(
            model_name="process_flow_model",
            name="run_time",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tables",
            name="other_config",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 12, 7, 6, 11, 473036, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 12, 7, 6, 11, 485857, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
