# Generated by Django 4.0.7 on 2022-11-14 12:58

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_processscheduler_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="login_trail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(max_length=255, null=True)),
                ("user_name", models.CharField(max_length=255, null=True)),
                ("time_logged_in", models.DateTimeField(auto_now=True, null=True)),
                ("time_logged_out", models.DateTimeField(editable=False, null=True)),
                ("logout_type", models.CharField(max_length=255, null=True)),
                ("ip", models.CharField(max_length=255, null=True)),
                ("inactivity_time", models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 14, 12, 58, 12, 214629, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 14, 12, 58, 12, 238627, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
