# Generated by Django 4.0.7 on 2022-12-12 08:37

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_audit_trail_alter_profile_date_joined_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="process_flow_event_status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("process_code", models.CharField(max_length=255, null=True)),
                ("subprocess_code", models.CharField(max_length=255, null=True)),
                ("block_element_id", models.CharField(max_length=255, null=True)),
                ("execution_date", models.DateField()),
                ("execution_time", models.TextField(null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("execution_information", models.TextField(blank=True, null=True)),
                ("executed_time", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="scheduler_event_status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("process_code", models.CharField(max_length=255, null=True)),
                ("subprocess_code", models.CharField(max_length=255, null=True)),
                ("block_element_id", models.CharField(max_length=255, null=True)),
                ("execution_date", models.DateField()),
                ("execution_time", models.TextField(null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("execution_information", models.TextField(blank=True, null=True)),
                ("executed_time", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="tab_header_color_config",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="from_ldap",
            field=models.BooleanField(default=False, editable=False, verbose_name="LDAP user"),
        ),
        migrations.AlterField(
            model_name="processscheduler",
            name="element_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 12, 8, 37, 36, 374500, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 12, 8, 37, 36, 388411, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
