# Generated by Django 4.0.7 on 2023-03-01 12:52

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_process_flow_event_status_scheduler_event_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="external_application_master",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hyperlink_code", models.CharField(max_length=255, null=True)),
                ("hyperlink_name", models.CharField(max_length=255, null=True)),
                ("hyperlink_desc", models.CharField(max_length=255, null=True)),
                ("hyperlink_url", models.CharField(max_length=255, null=True)),
                ("hyperlink_icon", models.CharField(max_length=255, null=True)),
                ("hyperlink_icon_color", models.CharField(max_length=255, null=True)),
                ("hyperlink_card_color", models.CharField(max_length=255, null=True)),
                ("hyperlink_text_color", models.CharField(max_length=255, null=True)),
                ("hyperlink_description_text_color", models.CharField(max_length=255, null=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="system_management_table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("screens", models.TextField(null=True)),
                ("preference_config", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="navigationsidebar",
            name="element_id_ct",
        ),
        migrations.AddField(
            model_name="application",
            name="app_ui_config",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approval_audit_log",
            field=models.TextField(null=True, verbose_name="Audit Log"),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approval_level_config",
            field=models.TextField(null=True, verbose_name="Approval Level Config"),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approved_by",
            field=models.CharField(max_length=526, null=True, verbose_name="Approved By"),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="approver_type",
            field=models.CharField(default="several", max_length=20, null=True, verbose_name="Approver Type"),
        ),
        migrations.AddField(
            model_name="approvaltable",
            name="current_decision_box_id",
            field=models.CharField(max_length=50, null=True, verbose_name="Current Decision Box Id"),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="design_mode",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="process_flow_design",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="process_icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="navigationsidebar",
            name="subprocess_icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approval_code",
            field=models.TextField(max_length=256, null=True, verbose_name="Approval Code"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approval_comments",
            field=models.TextField(null=True, verbose_name="Approval Comments"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approval_decision_mailer_config",
            field=models.CharField(
                max_length=1026, null=True, verbose_name="Approval Decision Mailer Config"
            ),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approval_status",
            field=models.CharField(max_length=100, verbose_name="Approval Status"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approval_type",
            field=models.CharField(max_length=256, verbose_name="Approval Type"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approver_group",
            field=models.CharField(max_length=256, verbose_name="Approver Group"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="approver_user",
            field=models.CharField(max_length=1026, null=True, verbose_name="Approver User"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="create_view_element_id",
            field=models.CharField(max_length=256, verbose_name="Create View Element Id"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="created_by",
            field=models.CharField(max_length=100, verbose_name="Created By"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="created_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Created Date"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="hierarchy_group",
            field=models.CharField(max_length=256, null=True, verbose_name="Hierarchy Group"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="json_data",
            field=models.TextField(verbose_name="Json Data"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="modified_by",
            field=models.CharField(max_length=100, null=True, verbose_name="Modified By"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Modified Date"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="modify_column",
            field=models.TextField(null=True, verbose_name="Modify Column"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="tablename",
            field=models.CharField(max_length=255, verbose_name="Table Name"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="transaction_id",
            field=models.CharField(default="NULL", max_length=255, null=True, verbose_name="Transaction Id"),
        ),
        migrations.AlterField(
            model_name="approvaltable",
            name="type_of_approval",
            field=models.CharField(
                default="static", max_length=256, null=True, verbose_name="Type Of Approval"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 3, 1, 12, 51, 53, 373702, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 3, 1, 12, 51, 53, 440427, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
