# Generated by Django 4.0.7 on 2023-03-15 06:31

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_external_application_master_system_management_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tagged_user",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="audit_operation",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 3, 15, 6, 31, 15, 385576, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 3, 15, 6, 31, 15, 405737, tzinfo=utc),
                null=True,
                verbose_name="date joined",
            ),
        ),
    ]
