# Generated by Django 4.0.10 on 2023-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_smtp_configuration_tables_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="notification_management",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notification_message", models.TextField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, max_length=30, null=True)),
                ("category", models.CharField(blank=True, max_length=30, null=True)),
                ("tenant_name", models.CharField(max_length=30, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("created_date", models.DateTimeField(auto_now=True, null=True, verbose_name="Created date")),
            ],
        ),
    ]
