# Generated by Django 4.0.10 on 2023-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_notification_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="external_application_master",
            name="external_app_ui_config",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user_model",
            name="is_developer",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Developer"),
        ),
    ]
