# Generated by Django 4.0.10 on 2023-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_approval_is_developer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_model",
            name="is_developer",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Is this user a Developer?"
            ),
        ),
    ]
