# Generated by Django 4.0.10 on 2023-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_user_model_is_developer"),
    ]

    operations = [
        migrations.CreateModel(
            name="system_application_master",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("app_name", models.CharField(max_length=255, verbose_name="App Name")),
                ("display_config", models.TextField()),
                ("app_drawer_ui_config", models.TextField(null=True)),
                ("app_theme", models.TextField(null=True)),
                ("tenant", models.CharField(max_length=100)),
            ],
        ),
    ]
